### ISSUE TITLE
Postcss files lint

### ISSUE THREAD

**Issue by dikmax** [AtomLinter/linter-stylelint#101]
Please check *.pcss and *.postcss too.

**Comment by juwain** [comment]
+1
Is there a workaround for now to check .pcss files from Atom?

**Comment by Arcanemagus** [comment]
When you run `Editor: Log Cursor Scope` from the command palette when you have a PostCSS file open what does it list?

**Comment by juwain** [comment]
Scopes at Cursor
- source.css.postcss
- meta.property-list.postcss
- meta.property-value.postcss
- punctuation.terminator.rule.postcss

**Comment by juwain** [comment]
Ok, I've just added `source.css.postcss` to grammarScopes array and it works!

**Comment by juwain** [comment]
If it is the only thing I can create a PR 😀

**Comment by Arcanemagus** [comment]
As PostCSS apparently doesn't require specifying a different syntax to `stylelint` that should be all that is needed. I can review a PR and get it merged in the morning :wink:.

**Comment by juwain** [comment]
Ok, it's morning in my timezone now =) Thanks, good night!
https://github.com/AtomLinter/linter-stylelint/pull/149

**Comment by Arcanemagus** [comment]
Published in v2.4.0 :tada:.
