### ISSUE TITLE
Freezes Atom in certain cases

### ISSUE THREAD

**Issue by silvenon** [AtomLinter/linter-stylelint#106]
```css
:global(.foo) {
}
```

If I erase the opening parenthesis, like this:

```css
:global.foo) {
}
```

It freezes Atom and I have to force quit.

I'm on OS X and using latest linter-stylelint.

**Comment by Arcanemagus** [comment]
I can't reproduce this using Atom v1.6.0-beta6 and linter-stylelint v1.13.1, were you able to @1000ch?

**Comment by ntwb** [comment]
Also cannot reproduce.

**Comment by 1000ch** [comment]
I also can't with newest linter-stylelint on Atom v1.5.4.

**Comment by Arcanemagus** [comment]
@silvenon Are you still seeing this?

**Comment by silvenon** [comment]
I'm sorry for not testing this through. This rule is causing the freeze:

```yml
selector-class-pattern:
  - "^[a-z]+([A-Z0-9][a-z0-9]+[A-Za-z0-9]*)?$"
```

The regular expression is supposed to be matching lowerCamelCase class names.

**Comment by Arcanemagus** [comment]
Looks like that rule crashes `stylelint` itself, it _looks_ fine from what I can see, but is it possible that with how `stylelint` is executing that regex you are running into a cascading backtrace?

**Comment by silvenon** [comment]
> Looks like that rule crashes stylelint itself

My CLI stylelint runs fine :confused: Yours crashes?

**Comment by Arcanemagus** [comment]
Well, it tried to run for over a minute before I killed it...

**Comment by Arcanemagus** [comment]
Just so we are for sure on the same page, with this folder:  [linter-stylelint_GH106.zip](https://github.com/AtomLinter/linter-stylelint/files/157621/linter-stylelint_GH106.zip)

Running `.\node_modules\.bin\stylelint .\test.css` locks up.

**Comment by silvenon** [comment]
Oh, you're right, I forgot to remove the parenthesis. This is not an issue with the linter then.

What's a cascading backtrace?

**Comment by Arcanemagus** [comment]
Sorry, looks like the right term is "Catastrophic Backtrace", and this explains it better than I ever could: http://www.regular-expressions.info/catastrophic.html

I'm not sure that is the reason, but _some_ part of that regex is forming a loop and running forever.

**Comment by silvenon** [comment]
@Arcanemagus thanks for this great resource, that could be it :+1:
