### ISSUE TITLE
Unable to run stylelint: Undefined rules

### ISSUE THREAD

**Issue by paulrobertlloyd** [AtomLinter/linter-stylelint#125]
I’ve just upgraded to linter-stylelint 2.0.0, and now getting the following errors:

* `Undefined rule "declaration-block-no-shorthand-property-overrides"`
* `Undefined rule "declaration-block-trailing-semicolon"`
* `Undefined rule "string-no-newline"`

I’m extending `stylelint-config-standard`, which is at v4.0.1. What’s going on… trying to keep up with the changes across this package and stylelint gets confusing fast!

**Comment by Arcanemagus** [comment]
If you are seeing those messages then you haven't updated `stylelint-config-standard`. Are you absolutely sure you have the current version installed?

**Comment by paulrobertlloyd** [comment]
I have nuked my node_modules folder and reinstalled. Yup, I’m using `stylelint-config-standard@4.0.1`

**Comment by paulrobertlloyd** [comment]
Actually, that seemed to fix it! The remaining error was in my override.

**Comment by Arcanemagus** [comment]
Thanks for reporting back :wink:.
