### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by davidtheclark** [AtomLinter/linter-stylelint#128]
I always appreciate a good changelog. When I see that the version bumped to 2.0 I would like to be able to come and quickly see what that means so I know whether I should upgrade or not.

**Comment by Arcanemagus** [comment]
Added a generated one, @1000ch if you want to do a better looking manual one (or find a better generator!) feel free :stuck_out_tongue:.

**Comment by 1000ch** [comment]
:ok_woman:

**Comment by ntwb** [comment]
:+1:
