### ISSUE TITLE
Update stylelint

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#134]
Will linter-stylelint automatically update to the latest version of `stylelint`? Because the most [recent release](https://github.com/stylelint/stylelint/releases/tag/5.1.0) contains a [fix](https://github.com/stylelint/stylelint/pull/913) for a [bug](https://github.com/AtomLinter/linter-stylelint/issues/68#issuecomment-197554109) that prevents me from using `stylelint-selector-bem-pattern` with `atomlinter`.

**Comment by ntwb** [comment]
No, it will not.

To get stylelint 5.1.x in Atom you'll need to uninstall the `linter-stylelint` package, restart Atom, then finally install the `linter-stylelint` package again.

_This is the downside of the Atom linters installing the linters themselves vs the Sublime Text way is that you should install the linter somewhere or globally yourself before adding the editor package._

**Comment by Arcanemagus** [comment]
@ntwb It really depends on the linter as to how it's implemented... `linter-eslint` will use a local project's install first, the global option (if enabled) next, and finally if none others were found then the bundled version.

I'd like to move this to that model, which is what https://github.com/AtomLinter/linter-stylelint/issues/51 is about, but I haven't had time and as it's still there I'm assuming @1000ch hasn't either :stuck_out_tongue:.

@ismay If you run `npm update` or uninstall/re-install `linter-stylelint` it should use the latest version. I can push out a new version of this that bumps the _minimum_ version to v5.1.0 later today (if I have time).

**Comment by ntwb** [comment]
Right, thanks for the clarifications @Arcanemagus :+1:

**Comment by ismay** [comment]
@Arcanemagus Thanks for the feedback. #51 sounds like a good long term solution. In the meantime, I'll reinstall it. Thanks!
