### ISSUE TITLE
Add less support

### ISSUE THREAD

**Issue by khakulov** [AtomLinter/linter-stylelint#135]
At the moment only css and scss file types are hardcoded. How difficult is to add add LESS support?

**Comment by ntwb** [comment]
This is more a stylelint issue, once stylelint supports Less syntax then Atom's linter-stylelint can look to what would be needed to support Less, see https://github.com/stylelint/stylelint/issues/810

**Comment by adriantoine** [comment]
Less support has been added in the latest `stylelint` version, can we have it?
https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#530

**Comment by Arcanemagus** [comment]
@adriantoine You're a tad late as this was released in [v2.2.0](https://github.com/AtomLinter/linter-stylelint/releases/tag/v2.2.0) of this package :wink:.

**Comment by khakulov** [comment]
@Arcanemagus less is still not supported. Plugins need some extra code.
Maybee here:
`grammarScopes: ['source.css', 'source.scss', 'source.css.scss'],`

**Comment by Arcanemagus** [comment]
Ah, good point, and it [looks like](https://github.com/stylelint/stylelint/blob/5.4.0/docs/user-guide/css-processors.md#parsing-non-standard-syntax) we need to specify a "syntax" to `stylelint` as well.

**Comment by ntwb** [comment]
> and it looks like we need to specify a "syntax" to stylelint as well.

Not something I've looked into, but presuming multiple syntaxes are supported or would be supported?

• CSS & SCSS
• CSS & Less
• CSS & SCSS & LESS

**Comment by jeddy3** [comment]
> Ah, good point, and it looks like we need to specify a "syntax" to stylelint as well.

Yep. We added two additional choices to the [`syntax` option](https://github.com/stylelint/stylelint/blob/5.4.0/docs/user-guide/node-api.md#syntax) in `5.3.0`.

So, in total stylelint supports four syntaxes:

- Standard CSS syntax (with standard syntax extensions) *[the default option]* (files usually has the extensions `.css`, `.pcss` and `.postcss`)
- SCSS (files usually has the extension `.scss`)
- Less (files usually has the extension `.less`)
- SugarSS (files usually has the extension `.sss`)

**Comment by Arcanemagus** [comment]
@jeddy3 Exactly, you can see where the SCSS syntax is being defined [here](https://github.com/AtomLinter/linter-stylelint/blob/v2.3.0/lib/index.js#L129-L134).

Also if PostCSS is handled by the default parser in `stylelint`, then fixing #101 should be as simple as figuring out the scopes for those files and adding them to the list of supported scopes.

**Comment by jeddy3** [comment]
> @jeddy3 Exactly, you can see where the SCSS syntax is being defined here.

I saw that :) I wasn't sure what "scopes" were though. I did try looking it up so I could send you a PR, but I got a little lost I'm afraid.

**Comment by onedesert** [comment]
I've add a PR to add LESS support. https://github.com/AtomLinter/linter-stylelint/pull/156
