### ISSUE TITLE
Opening css without a root stylelintrc keeps erroring on every keystroke

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#147]
In a project I'm working on I've got a `.stylelintrc` in the root of the project. I've also got a file opened that resides on my desktop (which does not have a root `.stylelintrc`).

An error notifying me of the missing rules for the file on my desktop keeps popping up on every keystroke, and I can't set them to ignore or anything. Also a stylelint-disable comment doesn't seem to help.

I guess that setting default stylelint rules in the `linter-stylelint` package's config would help maybe? But nonetheless this doesn't seem like it's intended behaviour.

![bug](https://cloud.githubusercontent.com/assets/7355199/14430206/f0596a9a-0000-11e6-806f-98a619a2fe03.png)

**Comment by Arcanemagus** [comment]
Hmmm, we ask `cosmicconfig` to see if it can find a configuration [here](https://github.com/AtomLinter/linter-stylelint/blob/v2.3.0/lib/index.js#L136-L141), then if it didn't find anything and the "Disable when no config" option is enabled it _should_ just return... so `cosmiconfig` must be finding a "configuration", but it's not one that `stylelint` knows how to understand. Can you possibly place a breakpoint [here](https://github.com/AtomLinter/linter-stylelint/blob/v2.3.0/lib/index.js#L142) and see what `result` looks like?

**Comment by ismay** [comment]
@Arcanemagus Ok, result is `null` at that position:

![untitled-2](https://cloud.githubusercontent.com/assets/7355199/14600623/ee1ccb16-055d-11e6-9c33-16363bf2a522.jpg)

**Comment by Arcanemagus** [comment]
Sorry, I misunderstood the setup when I first read this issue.

Basically `cosmicconfig` is properly finding no configuration for the file on your desktop, but it seems that you both have the "Use standard" option disabled (which would lint it with the default `stylelint-config-standard` settings) **_and_** you _don't_ have the "Disable when no config file is found" option enabled (which would cause it not to run on that file as it has no configuration for the linter).

Toggling either of those settings would fix your issue, as it stands though it is performing exactly as intended... you are asking it to lint the file but are providing it with no rules with which to do so.

**Comment by ismay** [comment]
Ah ok, yeah that makes sense. But out of curiosity, why does the 'disable when no config is found' exist? Shouldn't that just be the default?

Because the errors it generates when there isn't a config are pretty intense (especially as they're generated on every keystroke). Is there a usecase for these errors?

Anyway, thanks for helping, apologies for the unnecessary bug report!

**Comment by Arcanemagus** [comment]
I think the reason I'd say it should be left in is for people that do not want to use the bundled `stylelint-config-standard`, but expect there to be a valid configuration for all the files they edit _and_ would like to be notified when a configuration can't be found.

We should probably think about a throttle on that notification though...
