### ISSUE TITLE
Everything is an error

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [AtomLinter/linter-stylelint#151]
Many other Atom-Linter packages make the distinctions between errors (in red), and warnings (in yellow), the former being critical errors and the latter being stylistic or minor things that won't affect the function of the code.

Is there a reason why `linter-stylelint` makes every issue an error? Is it simply that `stylelint` only returns one kind of message?

**Comment by jeddy3** [comment]
Perhaps I can help. I'm not the maintainer of `linter-stylelint`, but I'm a contributor on `stylelint`. 

You can use the [`severity` secondary option](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#severities-error--warning) within your stylelint [configuration object](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#the-configuration-object) to downgrade a rule to a warning.

`linter-stylelint` displays them (as you would expect) in red or yellow, for errors and warnings respectively :)

For example, given the following config:

```json
{
  "rules": {
    "color-no-invalid-hex": true,
    "declaration-colon-space-after": ["always"],
    "declaration-no-important": true,
    "selector-max-specificity": ["0,1,0", {"severity": "warning"}],
  }
}
```

`linter-stylelint` displays:

<img width="628" alt="screen shot 2016-04-16 at 15 11 11" src="https://cloud.githubusercontent.com/assets/808227/14581459/d3612d0e-03e5-11e6-8929-8a24c236dcf1.png">

**Comment by The-Penultimate-Defenestrator** [comment]
Thanks. It seems kind of strange that the default behavior is to have everything with an "error" level severity, but that solves the issue.

**Comment by Arcanemagus** [comment]
This was hinted at throughout the issues filed, but just to explicitly state it: `linter-stylelint` simply forwards on the severity that `stylelint` gives us :wink:.

**Comment by The-Penultimate-Defenestrator** [comment]
Thanks. I've been discussing in other issues, I got that, but thanks for
clarifying 😉
