### ISSUE TITLE
Triple Slash Comments combined with ' cause problems

### ISSUE THREAD

**Issue by MattDiMu** [AtomLinter/linter-stylelint#157]
Triple slash comments (e.g. necessary for https://github.com/SassDoc/sassdoc documentation) combined with ' cause the linter to abort. 2 or 4 comments are no problem:

```
  /// it's an error
```

```
Error: Column start (21) greater than line length (19)
Error: Column start (21) greater than line length (19)
    at rangeFromLineNumber (/Users/xxx/.atom/packages/linter-stylelint/node_modules/atom-linter/lib/index.js:194:11)
    at createRange (/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:35:10)
    at /Users/xxx/.atom/packages/linter-stylelint/lib/index.js:74:14
    at Array.map (native)
    at stylelint.lint.then.error.type (/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:70:38)

```

Btw, I'm having this issue on my Mac with LF as well as on my Win7 with CRLF, so it's probably a different issue than #155.

**Comment by Arcanemagus** [comment]
Are you sure that `stylelint` supports SASS files? They aren't listed in their [Features](https://github.com/stylelint/stylelint#features).

**Comment by Arcanemagus** [comment]
And assuming that it does, do you see the mistaken columns when running from the CLI?

**Comment by MattDiMu** [comment]
I was referring to Sass-Files with SCSS-Syntax (.scss), which is listed as feature explicitly. From the terminal with 2 or 4 Slashes, i get an empty result (no errors), when having 3 I get the following result:

```
Macintosh:scss-mixins mattdimu$ stylelint "_justonecomment.scss" --syntax scss

_justonecomment.scss
1:3	Expected indentation of 0 spaces (indentation)
1:22	Unexpected newline in string (string-no-newline)
```

**Comment by Arcanemagus** [comment]
That 22 (1-indexed) translates perfectly to the 21 (0-indexed) in the warning, I'm guessing that line 1 has 22 characters in it? This looks like another issue that needs to be reported over on `stylelint` (but it _is_ different from what you are seeing in #155 as you surmised).

**Comment by MattDiMu** [comment]
@Arcanemagus Yes, line 1 has 20 chars in it and yes, it's caused by the quote character (but only if combined with exactly 3 slashes).

**Comment by Arcanemagus** [comment]
For reference, this was filed by @MattDiMu overe here: https://github.com/stylelint/stylelint/issues/1097
