### ISSUE TITLE
Allow comments in JSON

### ISSUE THREAD

**Issue by MadLittleMods** [AtomLinter/linter-stylelint#16]
Use the [`rc` package](https://www.npmjs.com/package/rc) which handles finding the config file and is lenient in allowing comments in JSON.

Currently, `linter-stylelint` is using [`JSON.parse`](https://github.com/AtomLinter/linter-stylelint/blob/6741535a14bccf7a8496ee226398c226ecadf90f/index.js#L39)

**Comment by 1000ch** [comment]
:+1:

**Comment by davidtheclark** [comment]
Would it be possible to just allow stylelint to find the config file itself? As of 2.0, it is using rc and should be able to find `.stylelintrc`. I think that here https://github.com/AtomLinter/linter-stylelint/blob/master/index.js#L81 you could just pass *no* config if a preset is not used, and then hopefully stylelint will take care of it.

**Comment by davidtheclark** [comment]
Nevermind ... stylelint can't seem to find the config because of the fact that Atom runs the process in a different place than if you were running it yourself.

**Comment by 1000ch** [comment]
Yes, AtomEditor working directory and workspace are different :astonished:

**Comment by davidtheclark** [comment]
rc uses the module https://github.com/sindresorhus/strip-json-comments to strip json comments. You could use that to satisfy this issue.

**Comment by Arcanemagus** [comment]
Marking this as closed per the above commit.

@1000ch for future reference try putting the text "Closes #16" or "Fixes #16" in the description instead of the title, it doesn't look like GitHub parses it from there properly.
