### ISSUE TITLE
Add config.cson support

### ISSUE THREAD

**Issue by samuelvgm** [AtomLinter/linter-stylelint#179]
Hi!

It would be awesome if I could configure Stylelint editing "~/.atom/config.cson" 

```  "linter-stylelint":
         extends: "stylelint-config-standard"
         rules:
               "declaration-block-properties-order": "alphabetical"
         useStandard: true
```

![captura de pantalla 2016-04-27 a las 12 07 09](https://cloud.githubusercontent.com/assets/6131039/14848950/a5ec483e-0c70-11e6-8655-473b0570af72.png)

**Comment by Arcanemagus** [comment]
Definitely _won't_ be implementing this, you should have the configuration in your project.

(Plus there is no way I want to maintain a list of the over a hundred rules `stylelint` supports!)

**Comment by samuelvgm** [comment]
Fair enough 

Sadly, in some team projects, I don't be able to add a config file.

Anyway, thanks for your work in this project :)

**Comment by Arcanemagus** [comment]
I believe it should search up in parent directories for a configuration, so you could try putting your "base" config in a parent directory.

If it's a team project that you can't add a config to the repo on, you could always just have one locally and simply not commit it to your VCS :wink:.

**Comment by samuelvgm** [comment]
Yep, it's a good advice. Thanks again Arcanemagus   :)
