### ISSUE TITLE
BaseDir error?

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-stylelint#180]
I was just editing a random file in a folder with no configs, settings, package.json etc.  Not a project, just a folder with css files.

I get this error:
![screen shot 2016-04-27 at 8 03 30 am](https://cloud.githubusercontent.com/assets/835148/14851976/9acbbfd0-0c51-11e6-9959-aa2c9d846fd2.jpg)

I have stylelint and stylelint-config-standard installed globally, though.  Shouldn't it fall back to global if not installed locally?

**Comment by Arcanemagus** [comment]
Are you sure you don't have a `.stylelintrc` file in any of the _parent_ folders? I believe it also checks your home directory.

If you don't, then it's possible that `apm` (Atom's package manager) failed to installed the `stylelint-config-standard` that is supposed to be bundled with this package, in which case a re-install of the package _should_ fix it for you.

**Comment by Arcanemagus** [comment]
Closing due to lack of response.
