### ISSUE TITLE
Less support

### ISSUE THREAD

**Issue by pawelphilipczyk** [AtomLinter/linter-stylelint#182]
The main page for stylelint says it has an experimental support for Less. Could it be enabled in the Atom plugin?

**Comment by Arcanemagus** [comment]
It's been enabled in `linter-stylelint` since v2.4.0, is it not working for you?

**Comment by pawelphilipczyk** [comment]
No, but I guess this means I'm doing something wrong. How does it get activated? 
I can't see a command to start linting. Or maybe I need to have .stylelintrc file first?

**Comment by Arcanemagus** [comment]
Although a `.stylelintrc` file is useful for configuring the linter for your specific project, if you go into your package settings and enable the `Use standard` option, then `linter-stylelint` will use the `stylelint-config-standard` base ruleset to lint your files.

Without that option enabled and no configuration you will see no results as there are no base rules enabled in `stylelint`.

**Comment by pawelphilipczyk** [comment]
OK, I've got it. The reason was "Disable linting when no config file found" in settings. Now I'm not sure if I activated it by accident or it is on by default?

**Comment by Arcanemagus** [comment]
You must have enabled it by accident, the default value is disabled for both settings :wink:.

**Comment by Arcanemagus** [comment]
Marking this as closed since you've got it figured out now, if you have any other questions feel free to keep commenting here or file a new issue.

**Comment by pawelphilipczyk** [comment]
That's what you get when you start playing with the settings before you actually use the tool :)
