### ISSUE TITLE
New release with updated stylelint

### ISSUE THREAD

**Issue by simonkberg** [AtomLinter/linter-stylelint#190]
Currently linting is broken when using stylelint-config-standard@7.0.0 since it depends on stylelint@^6.3.0 which introduced some new rules.

Example error in Atom:
```
Unable to run stylelint
Undefined rule "at-rule-name-space-after"
```

I notices greenkeeper has already updated the dependency, but it's unreleased.

Related to this I think the package should handle unknown rules better, eg. give a warning but keep checking rules it known about. Currently it throws an error and breaks linting completely.

**Comment by Arcanemagus** [comment]
The release is waiting on #142 being merged which enables linting CSS extracted from HTML (added in `stylelint` v6.3.0).

**Comment by Arcanemagus** [comment]
v2.8.0 is now published :tada:.
