### ISSUE TITLE
Add "Run stylelint only if config found" option

### ISSUE THREAD

**Issue by EvNaverniouk** [AtomLinter/linter-stylelint#195]
Using this extension on projects which don't use stylelint causes a ton of `No rules found within configuration. Have you provided a "rules" property?` to popup in Atom.

It would be nice if linter-stylelint could be disabled if a configuration found is not found.

**Comment by Arcanemagus** [comment]
Is the existing "Disable when no config" option not working...?

**Comment by EvNaverniouk** [comment]
Grr. Looks like Atom is being a jerk again and not showing the "Settings" button until the app is restarted. Nevermind.

**Comment by Arcanemagus** [comment]
Yea, that bug can be quite annoying at times :disappointed: :smile:.
