### ISSUE TITLE
Latest version throws error on each edit

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#200]
![error](https://cloud.githubusercontent.com/assets/7355199/15422214/ab81ab72-1e77-11e6-99c7-2290ef46db99.png)

It throws this error on each edit of any css file.

I'm using linter-stylelint 2.9.0
linter 1.11.14
atom 1.6.2
on windows 10

Let me know if you need more information!

**Comment by Arcanemagus** [comment]
Your Atom is out of date... although it should be new enough that that still works just fine. Can you update to the latest stable release and see if it works then?

**Comment by ismay** [comment]
> Can you update to the latest stable release and see if it works then?

Ah I assumed it auto-updated. Updating to the latest release solved this. Thanks!

**Comment by Arcanemagus** [comment]
That's good to know... I'll put a minimum version of Atom v1.7.0 on the next release. That's still quite bizarre that Atom v1.6.3 didn't have support for `.includes` :confused:.

Anyway, glad that did it for you!
