### ISSUE TITLE
length-zero-no-unit

### ISSUE THREAD

**Issue by eddiemoore** [AtomLinter/linter-stylelint#207]
I am getting an error with the linter saying `Undefined rule "length-zero-no-unit"`
Using stylelint v6.6.0
Rule exists: http://stylelint.io/user-guide/rules/length-zero-no-unit/

~~Not sure if it's issue with the linter or an issue with stylelint itself~~
It's an issue with the linter. Tested the rule against stylelint and it works.

**Comment by Arcanemagus** [comment]
Are you on version v2.11.0 of `linter-stylelint`? If so, can you provide a setup to test this with?

**Comment by eddiemoore** [comment]
Ahhhh. Yeah Atom didn't pick up that there was an update. v2.11.0 works. Thanks
