### ISSUE TITLE
Consider display rule ID and uri

### ISSUE THREAD

**Issue by pascalduez** [AtomLinter/linter-stylelint#208]
Hi,

similarly to how it's done in the `linter-eslint` add an option to display the rule ID and link to its doc in a badge.
http://stylelint.io/user-guide/rules/

**Comment by Arcanemagus** [comment]
An excellent idea, looking into this now.

**Comment by Arcanemagus** [comment]
Published in v2.12.0. 🎉

**Comment by pascalduez** [comment]
Wonderful!
