### ISSUE TITLE
disable warning about deprecated stylelint rule?

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-stylelint#217]
Every time I open a file supported by stylelint, I ger a status bar warning:

![screen shot 2016-06-29 at 1 28 46 pm](https://cloud.githubusercontent.com/assets/835148/16462031/71d8c8f6-3dfd-11e6-9738-a1b498d155bf.png)

While I appreciate heads-up, I am not even redefining that rule's default in my stylelintrc.  I hate showing a warning that isn't a warning, is there a way to disable this?  Or only show it once, or once per Atom session?

**Comment by Arcanemagus** [comment]
The warning isn't saying that the rule's default is being changed, but that the _entire rule_ is going away in v7.0. As the replacement ([length-zero-no-unit](http://stylelint.io/user-guide/rules/length-zero-no-unit/)) is also avaialble currently, why not just switch to that?

**Comment by smlombardi** [comment]
How do I do that?

**Comment by Arcanemagus** [comment]
Since it looks like the rule was simply a rename (the `(reference)` link in the message should give more information), you should just be able to replace `number-zero-length-no-unit` with `length-zero-no-unit` in your Stylelint configuration file.

**Comment by smlombardi** [comment]
That's why I am confused, ad my config file is

```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "number-leading-zero": null,
    "unit-whitelist": ["em", "rem", "s", "px", "%", "deg", "ms", "vh", "dppx", "dpi"],
    "at-rule-empty-line-before": null,
    "rule-non-nested-empty-line-before": null,
    "declaration-colon-newline-after": null,
    "max-empty-lines": 2,
    "selector-list-comma-newline-after": null,
    "selector-pseudo-element-colon-notation": "single",
    "selector-type-no-unknown": null
  }
}
```
No `number-zero-length-no-unit`

**Comment by Arcanemagus** [comment]
`stylelint-config-standard` versions below v9.0.0 haven't been updated, perhaps that's where it is coming from?

**Comment by smlombardi** [comment]
![screen shot 2016-06-29 at 2 17 48 pm](https://cloud.githubusercontent.com/assets/835148/16463552/468c6886-3e04-11e6-81d1-64bb0e4dc07a.png)

**Comment by smlombardi** [comment]
it seems my GLOBAL npm stylelint was not updated, although the one in the project was.

**Comment by Arcanemagus** [comment]
@smlombardi Marking this as closed, since it sounds like your issue is resolved. If this isn't the case please let me know 😉.

**Comment by sinedied** [comment]
Since `stylelint` latest 7.8 update, I have this warning:
```
Deprecation Warning: 'no-unsupported-browser-features' has been deprecated and in 8.0 will be removed. See: https://stylelint.io/user-guide/rules/no-unsupported-browser-features/
```
I understand that this will be removed in next (major) update, but is there a way to disable the warning during the migration time? I need to find a proper replacement, and it seems it won't be immediate.

**Comment by Arcanemagus** [comment]
@sinedied There isn't currently an enhancement request to add that functionality, can you file a new issue to track that?

**Comment by mcwebb** [comment]
@sinedied, a workaround is to define a formatter in your stylelint config that removes depreciation warnings e.g.

```js
  formatter: (reports) => {
    const cleanedReports = reports.map((report) => {
      report.deprecations = [];
      return report;
    });

    return stylelint.formatters.string(cleanedReports);
  }
```

But obviously this is quite a hack and should be use with caution.

**Comment by sinedied** [comment]
Thanks for the feedback, I think I'll post a feature request directly to the `stylelint` repo as they are the primary at fault.

**Comment by Arcanemagus** [comment]
I'm curious as to why you aren't just fixing your configuration to no longer refer to the deprecated rules?

**Comment by sinedied** [comment]
Because this rule is useful? :)

**Comment by mcwebb** [comment]
@Arcanemagus My personal use case is that my stylelint config extends https://github.com/primer/stylelint-config-primer which is where the depreciation errors are coming from but I can't fix them locally.
