### ISSUE TITLE
Constant errors when no config is present

### ISSUE THREAD

**Issue by kevinSuttle** [AtomLinter/linter-stylelint#221]
Literally every keystroke triggers an error when no stylelint config is present. 

<img width="468" alt="screen shot 2016-07-05 at 1 09 26 pm" src="https://cloud.githubusercontent.com/assets/95672/16593104/d0e3c18a-42b1-11e6-9ba3-ff95d1297c0d.png">

**Comment by Arcanemagus** [comment]
Either provide a configuration of your own, enable the "Use Standard" option, or enable the "Disable When No Config" setting. Any one of those three options should solve that for you 😉.

**Comment by kevinSuttle** [comment]
Right, but throwing an error on every keystroke still seems excessive.
