### ISSUE TITLE
Unexpected empty source (no-empty-source) at line 1 col 1

### ISSUE THREAD

**Issue by tnbiscuits** [AtomLinter/linter-stylelint#224]
This CSS:
```
select {
background-image: url("data:image/svg+xml;utf8,<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='24' height='24' viewBox='0 0 24 24'><path fill='#444' d='M7.406 7.828l4.594 4.594 4.594-4.594 1.406 1.406-6 6-6-6z'></path></svg>");
}
```
triggers the error: 
> Unexpected empty source (no-empty-source) at line 1 col 1

The error location is always listed as line 1 col 1 regardless of where the style definition is actually located, and the only way to clear the error seems to be to remove the rule completely.

Is this an issue with the linter or is there something wrong with my CSS style?

**Comment by Arcanemagus** [comment]
Interesting, looks to be a bug here (or in the Node API of `stylelint`) as I can't reproduce it on the CLI interface. Looking into it.

**Comment by Arcanemagus** [comment]
Looks like this is a bug in `stylelint` exposed by enabling the "Extract HTML" option, I'll make it only specify that option if you are in an embedded block in the next release, and will file an issue over there referencing this about the root bug.
