### ISSUE TITLE
Undefined rule "at-rule-no-unknown"

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-stylelint#225]
I just updated my project to stylelint 6.8.0 and config standard 10.0.0 an now I get this error:

<img width="463" alt="screen shot 2016-07-07 at 12 37 26 pm" src="https://cloud.githubusercontent.com/assets/835148/16661183/bcd92ce0-443f-11e6-9e21-bf353147d8e2.png">

**Comment by Arcanemagus** [comment]
Is your `linter-stylelint` package up to date? Those versions are included in v2.16.0 of this package.

**Comment by smlombardi** [comment]
Just saw that. Package didn't show up when I ran amp update, only later in status bar.
