### ISSUE TITLE
Undefined rule: selector-attribute-quotes

### ISSUE THREAD

**Issue by abaracedo** [AtomLinter/linter-stylelint#227]
It seems this rule is not yet added in the linter and throws the error

**Comment by Arcanemagus** [comment]
Duplicate of #226. `stylelint@6.9.0` is the first release to include that rule, and it's only 2 hours old 😛.

**Comment by Arcanemagus** [comment]
v2.17.0 is published including this version, enjoy 😉.

**Comment by abaracedo** [comment]
Thanks! Good job :+1:
