### ISSUE TITLE
Add notes to 2.17.0

### ISSUE THREAD

**Issue by kachkaev** [AtomLinter/linter-stylelint#229]
The latest release does not look 'proper' yet:

![stylelint](https://cloud.githubusercontent.com/assets/608862/16683435/c04983c6-44f7-11e6-9ce0-bcb716a2338e.png)

The notes will help figuring out what's changed.

Thanks for upgrading stylelint to 3.9.0! Would be really cool if you could have a look at #51 :–)

**Comment by Arcanemagus** [comment]
The [CHANGELOG](https://github.com/AtomLinter/linter-stylelint/blob/d8b5ff7adea2e249c4816021a5aa9416c00a9b1b/CHANGELOG.md) was actually updated, just the GitHub release didn't get it copied over, fixed now 😉.

#51 is a longstanding issue that is rather complex to get done right, as I'm still not happy with the most robust of the other implementations I haven't tried bringing it over here.
