### ISSUE TITLE
Ability to run with non-stylelint project

### ISSUE THREAD

**Issue by ai** [AtomLinter/linter-stylelint#231]
I have some projects without Stylelint. Some legacy or third-party project. But when I open them in Atom with latest `linter-stylelint` I see: “Unable to run stylelint”.

![gz3gmvz](https://cloud.githubusercontent.com/assets/19343/16716646/7f21db4e-470b-11e6-9065-3bebccd17ca2.png)

@Arcanemagus maybe we should disable linting, when project doesn’t have rules?

**Comment by Arcanemagus** [comment]
That's what the "Disable when no config file is found" option is for, is it not working for you?

**Comment by ai** [comment]
We have this plugin? 😆 Awesome!

Maybe we should add info about this options to warning message.

Also I think that we should enable it by default, because linter-eslint work in this behavior. What do you think about it?

**Comment by Arcanemagus** [comment]
Yea, I already planned on making that enabled by default with the upcoming major release when `stylelint@7` lands 😉.

**Comment by Arcanemagus** [comment]
Ha, glad I checked the issues, almost forgot to change the default with the new version.
