### ISSUE TITLE
Undefined rule "media-query-parentheses-space-inside"

### ISSUE THREAD

**Issue by radum** [AtomLinter/linter-stylelint#244]
I'm getting this error now

```
Unable to run stylelint

Undefined rule "media-query-parentheses-space-inside"
```

The new rules is `media-feature-parentheses-space-inside` but this is not defined anywhere. And I'm not using a config of my own. Its just the standard one coming with this plugin.

And I'm not sure from where this legacy rule comes from, and not sure what am I missing. All was good up until the last update.

**Comment by radum** [comment]
Found a upper folder stylelint config that was really old. Looks like stylelint goes up and up the tree and if it finds a config it will use that one. Updated that and all good now.

**Comment by hhlsch** [comment]
Hi, radum,  I have the same issue. But I cant find the old file what you said. Can you help me?

**Comment by radum** [comment]
@hhlsch You should search your entire tree not just the project folder for stylelint config files.

Also depending on how you run it, make sure you have the latest version / plugin for editor.

Not sure how else I could help, for me it was easy, I had 1 lvl up of my project folder a config file, once removed / updated all was good again.

**Comment by shikelong** [comment]
+1.

**Comment by Arcanemagus** [comment]
@shikelong "+1" gives very little information to go by on helping you out...

This issue would only be caused by having an outdated `.stylelintrc` somewhere in a parent folder of the file you were working on.
