### ISSUE TITLE
.stylelintignore is not respected

### ISSUE THREAD

**Issue by jaydenseric** [AtomLinter/linter-stylelint#251]
In a project with the following structure:

```
bundle/bundle.css
.stylelintignore
package.json
```

I have stylelint rules configured in `package.json` (which work) and `/bundle` set in `.stylelintignore`.

When I run `stylelint '**/*.css'` from the project root via CLI, errors in `bundle/bundle.css` are correctly ignored. If I open the file in Atom, linter-stylelint displays errors.

**Comment by Arcanemagus** [comment]
Confirming this as a bug, I've filed https://github.com/stylelint/stylelint/issues/1981 to find out whether I should be implementing this here or not though.

**Comment by Arcanemagus** [comment]
Turns out I completely missed the other new function introduced in v7.4.0, this will be fixed in the next release!

**Comment by shinnn** [comment]
![image](https://user-images.githubusercontent.com/1131567/29704662-b8b90146-89b5-11e7-9052-e36bbb2953f0.png)

@Arcanemagus I created a small project in which `fixture.css` should be ignored by stylelint, but linter-stylelint seems to unexpectedly lint `fixture.css`.

* Atom: v1.19.3
* linter-stylelint v4.0.2

**Comment by Arcanemagus** [comment]
@shinnn I'm not sure why you commented here, this bug _was_ fixed by the referenced commit. Commenting further in https://github.com/stylelint/stylelint/issues/2833.

**Comment by shinnn** [comment]
> this bug was fixed by the referenced commit. 

Simply, no.

**Comment by Arcanemagus** [comment]
> Simply, no.

Simply, **yes**. It _was_ fixed, it's broken now though.
