### ISSUE TITLE
Doesn't work with some ignore options

### ISSUE THREAD

**Issue by r3nya** [AtomLinter/linter-stylelint#252]
Hey!

I noticed some problem with `ignorePseudoElements` option for `selector-pseudo-element-no-unknown` rule.

My config:
```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "selector-pseudo-element-no-unknown": [true, { ignorePseudoElements: ["local"] }]
  }
}
```

My css file: 
```
:local {
  .modal { … }
  .panel { … }
}
```
And I got error in Atom, but `stylelint` from console works ok.

PS:
* linter-stylelint v. 3.1.0
* Atom v. 1.9.9

Thanks a lot for your work!

**Comment by Arcanemagus** [comment]
I'm seeing the exact same thing in Atom and through the CLI:
![image](https://cloud.githubusercontent.com/assets/427137/18291529/0d6cd9ea-743d-11e6-80b5-ee62452bf656.png)
![image](https://cloud.githubusercontent.com/assets/427137/18291536/17dc3344-743d-11e6-9533-fdbd4733ca78.png)

I used the following files when trying to reproduce this: [linter-stylelint_GH252.zip](https://github.com/AtomLinter/linter-stylelint/files/457821/linter-stylelint_GH252.zip)

Can you try the latest version of Atom and `linter-stylelint` and see if you are still able to reproduce this? If so, please provide the _exact_ files you are testing with.

**Comment by r3nya** [comment]
Hey @Arcanemagus!

I will do it tomorrow … Thanks. :wink:

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response, if you are still seeing this feel free to reopen and comment further 😉.
