### ISSUE TITLE
How can I change the color and/or font-size of the stylelint popup box?

### ISSUE THREAD

**Issue by 55Cancri** [AtomLinter/linter-stylelint#255]
The popup box displaying the errors is currently grey and a little large. I wish to:
1. make the box black
2. decrease the font size
3. decrease the line height

Is there a way I can do this? Some file I am not aware of? All of the current configuration options only seem to allow me to change the _rules_ of the linter, but not the style of the actual linter.

**Comment by Arcanemagus** [comment]
That's because this package has nothing to do with that 😛.

You'll want to look at [linter](https://github.com/steelbrain/linter), and possibly check out [linter-ui-default](https://github.com/steelbrain/linter-ui-default) which will soon be replacing the current UI.
