### ISSUE TITLE
about configBasedir

### ISSUE THREAD

**Issue by gucong3000** [AtomLinter/linter-stylelint#263]
http://stylelint.io/user-guide/node-api/#configbasedir
`configBasedir` should be the dir of project

https://github.com/AtomLinter/linter-stylelint/blob/master/lib/index.js#L234
But in here, It is be `dirname(filePath)`

**Comment by Arcanemagus** [comment]
Interesting, I wonder why this hasn't posed any problems yet. In any case it's relatively simple to set this to the root of the project (as Atom sees it), falling back to the current behavior if necessary.
