### ISSUE TITLE
Error: Line number (x) greater than maximum line (x)

### ISSUE THREAD

**Issue by dbox** [AtomLinter/linter-stylelint#264]
Hello!

Thanks for taking the time to make this great plugin! Appreciate all your hard work. I've searched through past issues here and in the stylelint thread as well. Seems I'm having similar problems as others, but haven't found any solutions that work yet.

I'm using SugarSS and standard:

![image](https://cloud.githubusercontent.com/assets/296130/18297887/e5c7d0ec-7479-11e6-8bb6-aadcdbfce79f.png)

I've tried it also by pulling in latest standard via npm and config file, which I've successfully done, but for this stripped-down example, I'm going straight from the Atom settings version.

The linter works perfectly. It just throws these alert-error boxes up constantly while typing:

![image](https://cloud.githubusercontent.com/assets/296130/18297929/3f71a226-747a-11e6-904a-6280efc2324d.png)

Any ideas? Let me know if there is any other information that I can give to assist in debugging. Happy to help in any way I can.

Thanks!

**Comment by Arcanemagus** [comment]
SugarSS (and other non-CSS syntaxes) can have issues since in reality what is going on is:

* Stylelint converts the SugarSS to CSS using the `sugarss` `postcss` plugin, creating a sourcemap back to the SugarSS
* Stylelint runs on this CSS
* Any errors are mapped back to the original SugarSS using the sourcemap

Can you run `stylelint` on the file on the CLI? (`stylelint global.sss --syntax sugarss`) I'm guessing that it will be reporting lines past the end of the file there as well.

**Comment by dbox** [comment]
Thanks for the reply.

```
➜  css stylelint _global.sss --syntax sugarss

_global.sss
 2:24  ✖  Expected a trailing semicolon                   declaration-block-trailing-semicolon  
 6:2   ✖  Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation
 7:21  ✖  Expected a trailing semicolon  
```

6:2 was on purpose to show an error
2:24 and 7:21 these aren't flagged in the editor (nor should they be since there are no semicolons in sugarss)

So, no, its not showing any of the weird "Line number" errors in the CLI.

**Comment by dbox** [comment]
Maybe it thinks there are more lines because of the (lack of) closing brackets?

**Comment by dbox** [comment]
Here it is in action:
![z6hhavmt4g](https://cloud.githubusercontent.com/assets/296130/18362947/980599de-75cd-11e6-99a7-4c66a6539b6d.gif)

**Comment by Arcanemagus** [comment]
I wonder if you are hitting https://github.com/stylelint/stylelint/issues/1889? That was fixed for a while but seems to have cropped back up.

**Comment by Arcanemagus** [comment]
Wow, all sorts of SugarSS mapping issues showing up in there. I'll file bugs on `stylelint` for each of them, linking back here.

**Comment by dbox** [comment]
Ah. It *is* pretty new I guess... Thanks for all the help!

**Comment by Arcanemagus** [comment]
Okay, so of the errors I caught in that GIF and were able to track down, they were all related to https://github.com/stylelint/stylelint/issues/1889 and https://github.com/stylelint/stylelint/issues/1892.

You can workaround most of them by simply enabling the "Ensure Single Trailing Newline" option in the core `whitespace` package. As most UNIX systems don't technically consider a file as having ended (properly) without that, it's a good idea to have that anyway :wink:.

You might also want to go into the Linter package and bump up the "Lint As You Type Interval", I personally have it up at 1500 ms myself.

**Comment by dbox** [comment]
Yeah, I think there is still some bug with Stylelint/SugarSS not being able to calculate proper line lengths. I'm happy to move this conversation there if you think that's the proper route. 

Even so, it would be nice if there was some way to just force-suppress the red box warnings.

"Ensure Single Trailing Newline" must default to true because that was already on.
I tried bumping up the "lint as you type interval", which indeed delayed the red boxes, but they still come up.

**Comment by Arcanemagus** [comment]
I'm going to mark this as closed since there isn't anything that can be done further here.

**Comment by dbox** [comment]
Okay. thanks. No way to suppress the warning boxes?

**Comment by Arcanemagus** [comment]
You could disable those two rules until those issues are resolved, they aren't returning correct results anyway (although they are returning _results_, just wrongly positioned ones, so you are losing some information).

I've yet to come up with a good solution for not spamming error messages, although I'm open to ideas.

**Comment by dbox** [comment]
its not those 2 rules. its basically everything, but thanks for help.

**Comment by Arcanemagus** [comment]
If you are seeing issues with those two rules disabled please report them! That means there are more rules out there misbehaving!

It looks like the race condition prevention put in place in a few other linters hasn't been done here, I'll push that out in a few minutes and if you see anything after updating to that upcoming version _please_ report it, as that means the rule itself is buggy.

**Comment by Arcanemagus** [comment]
Okay, if you are still seeing things after updating to v3.3.1, and you have those two rules disabled, then it is almost certainly a bug in another rule and should be reported so it can be fixed for everyone.

**Comment by Arcanemagus** [comment]
`block-no-empty` was fixed in https://github.com/stylelint/stylelint/pull/1978, and `no-missing-end-of-source-newline` was fixed by https://github.com/stylelint/stylelint/pull/1958, both of which should be in the next Stylelint release.
