### ISSUE TITLE
Plugin fails to run with cssnext's custom property sets in file.

### ISSUE THREAD

**Issue by akrigline** [AtomLinter/linter-stylelint#277]
I'm using stylelint in a project running cssnext via PostCSS. [Our stylelint configuration file is here](https://gist.github.com/akrigline/5de2c80f3e10ef3e3c1dfb16f3322112).

We use a lot of [cssnext's custom property sets](http://cssnext.io/features/#custom-properties-set-apply) and these seem to break the linter plugin, though they are perfectly fine during the actual build.

Whenever I open a file and make a modification to any css file with these in them, I repeatedly get the error "Unable to run stylelint; Expected pseudo-class or pseudo-element."

Example of one of our custom properties:
```
:root {
  --small-text: {
    font-size: 1rem;
    font-weight: 500;
  };
}
```

**Comment by Arcanemagus** [comment]
I'm seeing this on the command line, using the following files: [linter-stylelint_GH277.zip](https://github.com/AtomLinter/linter-stylelint/files/488069/linter-stylelint_GH277.zip)

I'm not entirely sure whether this would be a [stylelint](https://github.com/stylelint/stylelint) or [PostCSS](https://github.com/postcss/postcss), but I would recommend starting with `stylelint` and seeing if they think it's a bug there or if it should be moved further up to PostCSS.
