### ISSUE TITLE
.stylelintrc.yaml format not supported

### ISSUE THREAD

**Issue by jrajav** [AtomLinter/linter-stylelint#288]
The "Disable when no config file is found" option includes only .stylelintrc and stylelint.config.js

**Comment by Arcanemagus** [comment]
That code was written before that was an option 😛, thanks for the report!

**Comment by Arcanemagus** [comment]
Actually, `cosmiconfig` handles all of that for us, I'm not sure why it's not currently working but work being done on #285 will move entirely to letting `stylelint` handle the configuration for us.
