### ISSUE TITLE
Unable to parse stylelint configuration

### ISSUE THREAD

**Issue by jenbennings** [AtomLinter/linter-stylelint#296]
Just upgraded to 3.4.1 hoping it would fix some of the table bugs people have been having, alas:

<img width="488" alt="screen shot 2016-10-19 at 12 51 15 pm" src="https://cloud.githubusercontent.com/assets/3468612/19502776/d5b52de2-95fa-11e6-898d-b94d92d642af.png">

**Comment by diagramatics** [comment]
Might worth doing an `npm ls table` on the repository you're working on and see if it's updated. You'll need `table@3.8.3`. I'm assuming you can install `stylelint` again since the semver will pick that version up.

**Comment by jenbennings** [comment]
Worked, thanks!
