### ISSUE TITLE
Unable to run stylelint - Undefined rule "selector-no-empty"

### ISSUE THREAD

**Issue by jantimon** [AtomLinter/linter-stylelint#301]
I don't understand why I get the error - could you please add a message how such errors may be solved?

I also would like to have a "don't show the same error again" button.
Would that be possible?

<img width="465" alt="settings" src="https://cloud.githubusercontent.com/assets/4113649/19828552/0cdca7fc-9dc9-11e6-8774-ba8d72838164.png">

**Comment by Arcanemagus** [comment]
If you update to v3.5.0 of this package you should no longer be seeing that error. The `selector-no-empty` rule was only added in v7.5.0 of Stylelint, which was first included in v3.5.0 of this package.
