### ISSUE TITLE
.stylelintrc JSON highlight

### ISSUE THREAD

**Issue by ai** [AtomLinter/linter-stylelint#302]
If this plugin will also enable JSON syntax highlight for `.stylelintrc`, it will so good

**Comment by Arcanemagus** [comment]
Although you (and I) prefer to use JSON format in `.stylelintrc`, it [can also](http://stylelint.io/user-guide/configuration/#loading-the-configuration-object) be in YAML format, so even if this was possible, I wouldn't do it.

I would _highly_ recommend moving to one of the formats where the format is defined in the file name such as `.stylelintrc.js`. ESLint for example has deprecated a bare `.eslintrc`.
