### ISSUE TITLE
Make file extensions to parse configurable

### ISSUE THREAD

**Issue by jaydenseric** [AtomLinter/linter-stylelint#306]
It would be good to get linter-stylelint to work on .js files for [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components) users.

Can a simple comma separated list of additional file extensions to parse be added to the settings?

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #235, I might have time to re-implement that this coming week...
