### ISSUE TITLE
config file may not include comments

### ISSUE THREAD

**Issue by PatricSachse** [AtomLinter/linter-stylelint#310]
hey guys, 
I just tried your linter and it seems to be impossible to use a .stylelintrc-file including comments. Actually, the linter complains about "missing comma between flow collection entries" where no comma is missing (it is located in front of a comment): 

> missed comma between flow collection entries in "/data/git/atlantis/atlantis/.stylelintrc" at line 5, column 25:
        "at-rule-no-unknown": [ // disallow unknown at-rules

Just a snippet of my slylelintrc-file: 
```  "rules": {
    "at-rule-name-case": "lower",
    "at-rule-name-space-after": "always-single-line", // require a single space after at-rule names
    "at-rule-no-unknown": [ // disallow unknown at-rules
      true,
      {
        "ignoreAtRules": [
            "define-mixin",
```

Am I doing sth wrong here or is this kind of a bug?
Any help would really be appreciated! :)
Thanks a lot, Patric

**Comment by Arcanemagus** [comment]
This is just a wrapper around `stylelint` and has nothing to do with how the configuration file works. You can find documentation on the configuration format [here](http://stylelint.io/user-guide/configuration/), it looks like you want to either move to YAML format in your `.stylelintrc` file so you can get comments, or more likely move to the JS format.
