### ISSUE TITLE
Linters doesn't work

### ISSUE THREAD

**Issue by Zudin-Evgen** [AtomLinter/linter-stylelint#311]
Is there a windows 10 support included in those packages?If not, give me alternative.

**Comment by Arcanemagus** [comment]
@Zudin-Evgen `linter-csslint` is known to be broken (https://github.com/AtomLinter/linter-csslint/issues/156), fixing it requires a _lot_ of work though, and as `csslint` itself appears to be essentially dead and I don't personally use it, I haven't had much inclination to work on it 😛.

_This_ linter however should be working perfectly fine, on whatever OS you are on. Can you describe what you mean by "doesn't work"?

**Comment by Zudin-Evgen** [comment]
It doesn't work when i do mistakes in code. Look screenshot:
https://gyazo.com/60360a5e2d500232f432984b80103d88
And i have installed it already:
https://gyazo.com/4c43665f1c4952c7fd010b8bed726b08

How can i solve this?

**Comment by Arcanemagus** [comment]
Hmmm, it's definitely working for me:
![image](https://cloud.githubusercontent.com/assets/427137/22380332/f494b8ca-e471-11e6-8a93-2c060c3d40b3.png)

Do you have `*.css` in your Ignore list for Linter? Is this file ignored in whatever VCS you are using?

**Comment by Zudin-Evgen** [comment]
Hah!! Sorry man, i forgot to turn off this option, that goes by default:
https://gyazo.com/6f6cbd69aff845237834c74cfd0deb38

Now it's working fine!->>
https://gyazo.com/d2cbb1d32d3b10d06b4d1ccabb10d0ea

You forced me to look my settings. Thanks!You are a true friend!)

**Comment by Arcanemagus** [comment]
Your screenshot links are broken (you know you can paste images directly in comments here and they will be hosted by GitHub 😛), but I'm assuming you got it working. Glad to hear it 😉.
