### ISSUE TITLE
Use standard config as default?

### ISSUE THREAD

**Issue by gitanupam** [AtomLinter/linter-stylelint#320]
How about having the setting 'Use standard' checked by default and 'Disable when no config file is found' unchecked by default?

This is to ensure that it works 'out of the box' and the users can then apply their own config file if they feel the need for it.

**Comment by Arcanemagus** [comment]
I'm pretty strongly against "global" configs like this. If a project is intended to follow a specific style, that style should be defined and enforced by configuration within the project, hence the default settings.

However, there are people that don't really care and just want it to "work", not caring about the fact that nobody else working on the project will get the same configuration, or even themselves in the future coming back to the project with potentially different settings now. For those cases the setup you've requested is provided.
