### ISSUE TITLE
Support for CSS property order

### ISSUE THREAD

**Issue by justinsthomas** [AtomLinter/linter-stylelint#326]
Not sure if this is on the roadmap, or if anyone else would find it useful, but is there any talk of supporting rules around CSS property ordering? I noticed this used to be supported in `stylelint` itself, but has been deprecated in favor of `stylelint-order`: https://github.com/hudochenkov/stylelint-order. To be honest, I haven't thoroughly digested the source of `linter-stylelint` yet, but is this supported out of the box? If it's not on anyone's radar, I'm happy to take a stab at it.

**Comment by Arcanemagus** [comment]
I think with `stylelint` relying more and more on plugins for support of certain features, it will be better to focus efforts on properly fixing #51 so this package can simply use the version of `stylelint` in your project.
