### ISSUE TITLE
Un-ignore directories?

### ISSUE THREAD

**Issue by adamnel** [AtomLinter/linter-stylelint#338]
In my Atom install, stylelint will ignore scss files contained in the node_modules directory. How do I disable this behavior?

**Comment by Arcanemagus** [comment]
Atom itself by default ignores things that are ignored by your version control system, which usually `node_modules` is. This is controlled by the "Exclude VCS Ignored Paths" setting in Atom. Linter follows this setting, and as that is what runs `linter-stylelint` you would need to disable that setting before you could lint something in a `node_modules` folder.
