### ISSUE TITLE
Could not find "stylelint-config-recommended". Do you need a `configBasedir`?

### ISSUE THREAD

**Issue by Eschon** [AtomLinter/linter-stylelint#357]
I just now updated to `linter-styleint` version 4.0.0 and I have configured it to use the standard config. Now when I open a css file I get the following error:

Could not find "stylelint-config-recommended". Do you need a `configBasedir`?

With a bit of searching around I found that `stylelint-config-standard` was changed to extend `stylelint-config-recommended` (see https://github.com/stylelint/stylelint-config-standard/pull/80/files) but it seems like it is not installed as a dependency when installing your package.

**Comment by bbroens** [comment]
Same problem for me. Also, it does not seem to load my config files anymore. Probably due to missing standard config.

**Comment by Arcanemagus** [comment]
@Eschon It's a [`dependency`](https://github.com/stylelint/stylelint-config-standard/blob/2951a657c892d1a00affefc76e169131ec45d2c3/package.json#L21) of `stylelint-config-standard`, as such it _shouldn't_ be a dependency here.

Occasionally Atom's APM fails to install some dependencies semi-rarely, you can try re-installing the package. Even better, you should install that as a `devDependency` in your project so everyone linting it gets the same config.

@bbroens Your "does not seem to load my config files" would be a separate issue. Please note that as of v4 `linter-stylelint` no longer merges `stylelint-config-standard` in over the top of your project configuration if you have "Use standard" enabled, so your lint results may be different (but should be what you would get running `stylelint` by itself).

**Comment by Eschon** [comment]
@Arcanemagus I tried reinstalling the package but it still doesn't work.  
Looking into the `node_modules` directory of the package I found that `stylelint-config-standard` is installed but somehow stylelint doesn't find it.

**Comment by Arcanemagus** [comment]
Can you provide a zip of a project (or gist, or repo) that reproduces this so I can look into it?

**Comment by Eschon** [comment]
This issue isn't linked to a specific project. It just happens everywhere where I don't have my own stylelint config like when I just open a random css file. So I have no idea what I could give you if you don't already have this issue.

**Comment by Arcanemagus** [comment]
If you open [this file](https://github.com/AtomLinter/linter-stylelint/blob/f8b29886499c54e7e8192f3e8c3f7974c4621006/spec/fixtures/bad/stylelint-config-standard.css), which purposely has no config, do you see this? I can't reproduce it opening that file.

Settings tested:
![image](https://user-images.githubusercontent.com/427137/28471655-b34b0a08-6df2-11e7-9f5e-abb2d172766d.png)

**Comment by Eschon** [comment]
Yes it happens with the file. My settings for the package are the same as yours.

**Comment by Eschon** [comment]
I just realised that I have stylelint installed globally. Could it be that the package uses the global installation which then can't find the config?

**Comment by Arcanemagus** [comment]
Something is very different between our systems then, because that file works just fine for me...

Does version v3.12.0 of this package give you the same problems? You can test with `apm install linter-stylelint@3.12.0`.

----

This package _only_ uses the bundled version (see #51), but it _should_ load global plugins, I don't think I've manually tested that in a long time though.

**Comment by Eschon** [comment]
In version 3.12.0 it works fine. 

I'll try if it works if I remove my global version of stylelint but I have run into a bug with `npm uninstall -g` so I'll have to resolve that one first

**Comment by Eschon** [comment]
Ok I just tested it without a global version of stylelint and I still get the same error.

Is there some more information I can provide to help finding the cause of this?

**Comment by bbroens** [comment]
Still same problem here as well. I only use the Atom plugin. Have no other instance installed with npm

**Comment by Arcanemagus** [comment]
Can you open up Atom's Developer Tools (same keyboard shortcut as Chrome) and:

* Place a breakpoint [here](https://github.com/AtomLinter/linter-stylelint/blob/v4.0.1/lib/index.js#L150)
    * Check if it is finding a configuration, and if so, that it is the one you are expecting.
* Place a breakpoint [here](https://github.com/AtomLinter/linter-stylelint/blob/v4.0.1/lib/helpers.js#L138) and verify that that is where it is returning this error.

It would be nice to also know the Atom versions and OS you are using.

**Comment by Eschon** [comment]
For the first breakpoint it doesn't find a config as expected.

The error is not returned on the second breakpoint because `error.line` is undefined [here](https://github.com/AtomLinter/linter-stylelint/blob/v4.0.1/lib/helpers.js#L136)

> It would be nice to also know the Atom versions and OS you are using.

OS: OS X 10.11.6
Atom: 1.18.0

**Comment by Arcanemagus** [comment]
How about if you place a breakpoint [here](https://github.com/AtomLinter/linter-stylelint/blob/v4.0.1/lib/index.js#L168), what does `options.configBaseDir` look like?

**Comment by steals** [comment]
I have the same issue. And options.configBaseDir shows the root folder where atom was opened.
I've also tried to uninstall / install package but it doesn't help.

**Comment by Arcanemagus** [comment]
Could somebody that is affected by this contact me on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638)? Everything _looks_ correct and I am unable to reproduce this...

**Comment by Eschon** [comment]
Should be possible for me but I have the issue at work and I'm on vacation next week. So we'd have to do it the week after.

**Comment by dutchauser** [comment]
I am also having the same problem. I have installed v3.12.0 as suggested and can confirm that the package works on that version.

**Comment by gbittmann** [comment]
I'm running on Windows and installed via the packages install interface. The version is 4.0.1 and I've checked the Use Standard box in settings. 

I get the same error for all css files that I open.

**Comment by bobbyquennell** [comment]
see issue. installed on Windows 10 and MacOS Sierra. encounter the same issue.
a quick workaround could be giving an absolute path  in the stylelint config file

**Comment by Arcanemagus** [comment]
It doesn't look like OS is relevant to this as there are people with it both working and not working on both macOS and Windows, so it's something to do with the specific system configuration that just isn't replicated on my computer.

**Comment by litar1** [comment]
I just want to add that the same error appears in Ubuntu 16.04 :(

**Comment by Arcanemagus** [comment]
Until somebody that can reproduce this traces down what is going wrong, or I can get access to a machine where it is happening this will remain unfixed.

**Comment by bdsexton** [comment]
I encountered this error message with a first-time installation and since I am new to both linter-stylelint and stylelint in general I had no idea what was causing it or even why so many rules were being applied with or without my own config (https://stylelint.io/ says "Only enable the rules you want"). After discovering and disabling the "Use standard" setting, though, everything seems to work great using just the rules I have explicitly defined in .styleintrc.json.

Sorry for the noise, @Arcanemagus. I just figured a little note might help other new users who find this issue via a search for the error message as I did.

**Comment by etlund** [comment]
I've been struggling with this bug too.  This morning I installed stylelint by itself (`npm install stylelint`) and stylelint-config-recommended and it seems to be working for me.  I realize that's maybe not how it's supposed to work (i.e. the Atom package should be standalone), but at least I can get back to work!

**Comment by Arcanemagus** [comment]
> After discovering and disabling the "Use standard" setting

@bdsexton On of the breaking changes in the last major version pushed out here was to _stop_ merging the `stylelint-config-standard` with your project's configuration. It should use your project's configuration exclusively if it exists, otherwise it will use `stylelint-config-standard` (If you have that option disabled the "Disable when no config" option comes into play).

> This morning I installed stylelint by itself (npm install stylelint) and stylelint-config-recommended and it seems to be working for me. I realize that's maybe not how it's supposed to work (i.e. the Atom package should be standalone)

@etlund If you have a stylelint configuration in your project, you definitely should be installing `stylelint` and any configuration packages in your project, that's the recommended way of doing things. The bundled stuff is usually only a fallback, this project currently will no matter what use the bundled `stylelint` (#51), but it should be using the configuration from your project.

**Comment by NQuackenboss** [comment]
I too am having this issue. This was my first time using this package. I turned on the "Use standard" and "Show message when a file is ignored" settings. Then, I attempted to lint a css file and I got this error. Stylelint-config-recommended and stylelint-config-standard are both in the packages folder. I also tried to install both stylelint-config-recommended and stylelint-config-standard (as well as stylelint) globally with npm which did nothing. Atom and all of my packages are up to date. I tried an uninstall and reinstall of the linter-stylelint package and that didn't help either.

**Comment by Arcanemagus** [comment]
Many thanks to @darrencoen who let me poke around on their system for a bit and got this bug diagnosed and figured out!

A fix is up in #368!

**Comment by Arcanemagus** [comment]
Published in v4.0.2, please let me know if you are still having problems after updating to that version (or greater).

Thank you everyone for your patience while this got figured out!

**Comment by yenly** [comment]
Everything was working fine and then I started to see these errors. I updated to 4.2.0 and am still seeing the issues. How can I fix this?

**Comment by JourneyOver** [comment]
Getting this issue as well on 4.2.0

**Comment by Arcanemagus** [comment]
@yenly, @JourneyOver, @CxRes: The specific cause of this issue _should_ be fixed, it sounds like you might be hitting a related trigger though. Please file a new issue with an example repository / ZIP archive that is showing the issue or at minimum outline your directory structure showing where you have Atom opened as the root project folder, where your `stylelint` configuration is, and where the file you are linting is.

**Comment by JourneyOver** [comment]
@Arcanemagus I just went ahead and decided to setup a full project folder that had all the stylelint stuff downloaded into it instead of trying to be standalone with just atom. So for me at least it's working now. :x

**Comment by jrrera** [comment]
I fixed this issue by `npm install`ing the dev dependencies of my project which included `stylelint` and `stylelint-config-standard`

**Comment by samdutton** [comment]
I just got the same error. 

I solved it by `npm install`ing stylelint and stylelint-config-standard within my project directory, not globally (much like @jrrera).

**Comment by mohamednaser** [comment]
After more 4 hours of investigation, I have solved this problem by just install stylelint-config-recommended npm package.

link of the package [here](https://www.npmjs.com/package/stylelint-config-recommended)

**Comment by SgtPooki** [comment]
For anyone else running into this issue who have done everything else properly... (i.e. you already have the proper dependencies installed), you need to specify the full npm package name, not the postfix.. i.e. for [stylelint-config-strict](https://github.com/keithamus/stylelint-config-strict), you have you use `"stylelint-config-strict"`, not `"strict"` as they [specify in their README](https://github.com/keithamus/stylelint-config-strict#usage).
