### ISSUE TITLE
Cannot use config file: Unable to parse stylelint configuration Unexpected token :

### ISSUE THREAD

**Issue by bbroens** [AtomLinter/linter-stylelint#362]
That is the error I get when I use any config file. This is the stylelint.config.js I am currently using:

```
{
    "extends": "stylelint-config-standard",
    "rules": {
        "indentation": 2
    }

}
```

**Comment by Arcanemagus** [comment]
Using a JS file means you need to export the configuration object, the format you have up there is JSON, not JS.

See https://stylelint.io/user-guide/configuration/ for the documentation.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response.
