### ISSUE TITLE
Linter fails to run on files that are ignored by git

### ISSUE THREAD

**Issue by begin-again** [AtomLinter/linter-stylelint#366]
Stumbled on this by accident while testing some build scripts. I created a folder with some sample css files. I added this folder to my .gitignore. When I opened any css file from this folder in Atom, the linter would not process the file. If I moved a file into a non-ignored folder and re-opened in Atom, the linter processed the file and I see the report. Move the file back to the ignored folder and re-open. Once again the linter does not process the file.

linter-stylelint: 4.0.1
stylelint: 8.0.0
Atom: 1.19.0 x64 
Windows: 10

**Comment by Arcanemagus** [comment]
Linter follows the core Atom setting of "Exclude VCS Ignored files" that controls many aspects of Atom including `find-and-replace` as well as potentially the `tree-view` itself if you enable the secondary option in it's settings.
