### ISSUE TITLE
Does not work with stylelint 8.3.1 / config-standard 18.0.0

### ISSUE THREAD

**Issue by rsolomon** [AtomLinter/linter-stylelint#378]
```
Undefined rule font-family-no-missing-generic-family-keyword
```

I'm unclear why this plugin is pegged to such a specific version. Should it not just use the version that's installed in the current directory first?

**Comment by Arcanemagus** [comment]
Nobody has taken the time to implement that properly (see #51) 😉.

Anyway, the missing rule is fixed in #372.
