### ISSUE TITLE
Configuration via package.json

### ISSUE THREAD

**Issue by keithamus** [AtomLinter/linter-stylelint#38]
Hey @1000ch! Thanks for making this project. 

linter-stylelint tries to load configuration from a .stylelintrc file. Since v3 (see https://github.com/stylelint/stylelint/issues/490) this isn't the only way to load config files! We can now use the package.json `stylelint` directive to declare options within our package.jsons, just like eslint or browserify.

atom-linter-eslint currently has [code for handling this](https://github.com/balupton/linter-eslint/blob/1ee972483d2a7576edd96dc84a4eb33edbb10f81/lib/worker.js#L47-L53). Maybe linter-stylelint could borrow it to do the same thing for stylelint?

**Comment by 1000ch** [comment]
@keithamus I'll implement within today :)

**Comment by keithamus** [comment]
:star::100:

**Comment by 1000ch** [comment]
@keithamus Published as `v1.5.0`.
