### ISSUE TITLE
.stylelintignore is not respected when using standard config

### ISSUE THREAD

**Issue by cpearce31** [AtomLinter/linter-stylelint#384]
I have the "Use standard" option checked in the `linter-stylelint`'s settings in Atom. It is working properly, except that it doesn't seem to respect any rules I put in a `.stylelintignore` file in the root of my project. I have tried to adding `console.log(process.cwd())` to `index.js` in `lib/index.js` and it confirms that `process.cwd()` is the root directory of my project. I tried running the Stylelint CLI using a globally installed `stylelint-config-standard` on my project, and it properly respects my ignore file. 

I'm using `linter-stylelint` version 4.2.0.

**Comment by emuvente** [comment]
@cpearce31 are you still having this issue with `linter-stylelint` version 4.3.0?

**Comment by cpearce31** [comment]
Yes, just tested the same project with 4.3.0 and the `.stylelintignore` is still not working.

**Comment by cpearce31** [comment]
It's an upstream issue. See https://github.com/stylelint/stylelint/issues/2833. Thanks!
