### ISSUE TITLE
How to pass a config

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#4]
Is there a way to pass a config to stylelint? Maybe something like a `.stylelintrc` would be a good temporary solution, until the stylelint api's been finalized.

related: https://github.com/postcss/postcss/issues/477 & https://github.com/stylelint/stylelint/issues/288

**Comment by 1000ch** [comment]
OK, I'll implement it as temporary solution.

**Comment by 1000ch** [comment]
Priority order:

1. Load preset config if `usePreset` is checked.
2. Load `.stylelintrc` if exists.
3. Empty config.

**Comment by 1000ch** [comment]
This issue is fixed at `v0.4.0`.
