### ISSUE TITLE
Lints when package disabled

### ISSUE THREAD

**Issue by brandonkal** [AtomLinter/linter-stylelint#409]
This one has my head scratching... `linter-stylelint` seems to continue linting when the package is disabled. Only by explicitly disabling stylelint in the `linter` package (by entering it into the disabled providers field) does stylelint stop.

I really just want to disable it for this project.

Furthermore, it seems `.stylelintignore` is ignored. It exists in the root directory of my project and the entire contents are `*`. I've also tried `*.css` with no success.

I even tested to make sure the atom package was providing the linting by creating an invalid `.stylelintrc` file:
```
{
 "provider": null
}
```

Sure enough, Atom alerts me that the stylelint plugin cannot parse the config file:
```
Unable to parse stylelint configuration
No rules found within configuration. Have you provided a "rules" property?
```

The only way I could get this to work was to delete my `~/.stylelintrc` file and set "Disable when config not found." That worked, but disabling the package did not.
I would like to leave my global stylelint in place and just selectively disable it for projects with vendored stylesheets.

**Comment by contra** [comment]
@brandonkal Are you still having this issue? Seems like it would be an issue in atom itself.

**Comment by brandonkal** [comment]
That may be. I no longer use Atom though.
