### ISSUE TITLE
Plugin keeps enforcing "at-rule-empty-line-before" even though it is not defined in my config

### ISSUE THREAD

**Issue by onlywei** [AtomLinter/linter-stylelint#48]
I just downloaded this linter plugin, and it is giving me warnings related to the `at-rule-empty-line-before` rule. This rule is no where in my `.stylelintrc`. Why am I getting these warnings?

**Comment by Arcanemagus** [comment]
Does `stylelint` from the command line output the same thing?

**Comment by onlywei** [comment]
I run `stylelint` through postcss. It does not output the same thing.

**Comment by onlywei** [comment]
Ah, I see what the issue is. The "Use Preset" checkbox was on by default, and I couldn't find the settings button.

I think "Use Preset" should be changed to unchecked by default.

**Comment by Arcanemagus** [comment]
I'd say there is a pretty good case for that since currently it is merging a project's supplied config with the chosen preset. What do you say @1000ch?

**Comment by 1000ch** [comment]
I think It should be unchecked, too.

1. **Use Preset** should be unchecked as default.
2. If checked, it is supplied as base config. If project config also exist, preset will be merged into it.

**Comment by 1000ch** [comment]
@onlywei Published as `v1.6.0`. 
@Arcanemagus Thank you for fix. :+1:
