### ISSUE TITLE
don't fix "color-hex-case": "lower" rule in rgba functinos.

### ISSUE THREAD

**Issue by adFedorovich** [AtomLinter/linter-stylelint#488]
## Issue Type
Bug

## Issue Description
Has rule "color-hex-case": "lower" in .stylelintrc, after save colors in rgba functions remain in upper case

## Bug Checklist
- [ ]  create rgba function in scss file (color: rgba(#E2E2E2, .5));

**Comment by Arcanemagus** [comment]
This sounds like it needs to be filed over on `stylelint`, this package is just a wrapper around that with it doing all of the work.
