### ISSUE TITLE
Underline spans entire screen

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#5]
Errors are underlined. But sometimes the underline goes across the entire screen:
![screen shot 2015-08-18 at 15 08 41](https://cloud.githubusercontent.com/assets/7355199/9330658/12870196-45bb-11e5-941d-09c3545a8ad0.png)

Instead of only underlining the rule (like eslint does):
![screen shot 2015-08-18 at 15 09 42](https://cloud.githubusercontent.com/assets/7355199/9330675/337dda64-45bb-11e5-8447-ac101398583a.png)

It would be better if it only underlined the rule, and not span the entire screen, I'd say.

**Comment by 1000ch** [comment]
@ismay Fixed with newest version.
If you got same problem, paste the CSS which causes this problem?

**Comment by ismay** [comment]
This fixed it for me, thanks! It did cause some new unexpected behaviour, I'll open a different issue for that.

**Comment by 1000ch** [comment]
:+1:
