### ISSUE TITLE
stylelint version way out of date and incompatible with current stylelint rules

### ISSUE THREAD

**Issue by dwightware4** [AtomLinter/linter-stylelint#548]
Hi, I recently upgraded my project packages and now get the following error:

`Unable to parse stylelint configuration`
`Undefined rule unicode-bom`

This error is because linter-stylelint is using v9.10.1 of stylelint, which is over a year out of date behind the current stylelint version which is 13.0.0. 

Can we please update linter-stylelint to use the current version of stylelint? I'd be happy to open a PR with the update.

**Comment by contra** [comment]
I believe https://github.com/AtomLinter/linter-stylelint/pull/441 fixes this

**Comment by Arcanemagus** [comment]
I don't personally use this package, and it looks like the current maintainers haven't been keeping it up to date and I haven't been paying enough attention to it. Sorry about the delay and I'll be working on getting this into a usable and current state again tonight!

**Comment by Arcanemagus** [comment]
All devDependencies are current, and `stylelint` has been updated as well. Looking into (correctly) fixing #441 now so this won't be an issue in the future.

Since this particular issue is solved I'm marking this as closed. If anyone is interested in helping to maintain this please let me know!

**Comment by contra** [comment]
@Arcanemagus Thanks for merging! If you need any help maintaining feel free to throw me onto it.
