### ISSUE TITLE
Does not show all warnings in the gutter

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#6]
Line 25 and 26 for example, don't have a yellow dot in the gutter (but they do have a warning).

![screen shot 2015-08-19 at 09 55 35](https://cloud.githubusercontent.com/assets/7355199/9351306/847dd0d4-4658-11e5-8106-741823acae5d.png)

**Comment by 1000ch** [comment]
@ismay Still getting error with newest version?

**Comment by ismay** [comment]
This seems to be fixed now. All errors are correctly shown in the gutter.

**Comment by 1000ch** [comment]
:+1:
