### ISSUE TITLE
Inconsistent underline for import rules

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#7]
Not sure whether this is intentional, but it doesn't always underline rules that have an error (this is with stylelint-config-suitcss):

![screen shot 2015-08-25 at 09 31 04](https://cloud.githubusercontent.com/assets/7355199/9461165/7b3d304c-4b0c-11e5-9b31-4b9eff22e4a8.png)

```
/**
 * Text utility
 * =============================================================================
 */

 @import 'suitcss-utils-text';

/**
 * Text sizing
 */
.u-textXxs {
  font-size: var(--font-sizeXxs);
}
```

![screen shot 2015-08-25 at 09 31 52](https://cloud.githubusercontent.com/assets/7355199/9461168/8190c29c-4b0c-11e5-9638-3fc58a67588c.png)

```
/**
 * Responsive sizing utilies
 */

@import '../base/breakpoints';

/**
 * Small screens and up
 */
.u-sm-full {
  width: 100% !important;
  flex: none !important;
}

.u-sm-shrink {
  flex: 0 1 auto !important;
}

.u-sm-1of2 {
  width: 50% !important;
  flex: none !important;
}
```

**Comment by 1000ch** [comment]
@ismay Please update to newest `linter-stylelint` and tell me if having the same problem?

**Comment by ismay** [comment]
Seems to be fixed after updating :+1:
