### ISSUE TITLE
Invalid option value "float" for rule "rule-properties-order": should be an object

### ISSUE THREAD

**Issue by onlywei** [AtomLinter/linter-stylelint#71]
I get this error on line 1 of every single one of my CSS files after upgrading to 1.10.2. Everything used to work fine before. Here's my `rule-properties-order` config in `.stylelintrc`:

```
    "rule-properties-order": [
      "display",
      "float",
      "position",
      "top",
      "right",
      "bottom",
      "left",
      "margin",
      "border",
      "padding"
    ],
```

**Comment by Arcanemagus** [comment]
linter-styleint v1.10.0 updated the included `stylelint` to v4.0.0, are you perhaps seeing something that was changed in `stylelint` itself?

**Comment by onlywei** [comment]
@Arcanemagus yes, you are correct. My version of `stylelint` that I want to use is `3.2.1` though. It's what I have installed in my `node_modules`.

**Comment by Arcanemagus** [comment]
Unfortunately this plugin currently only uses the built in version of `stylelint`, a PR moving it to the model of linter-eslint or linter-coffeelint which can load a project's specific version would be great to see.

For now I would say you should probably run `apm install linter-stylelint@1.9.2`, which will bring you back down to `stylelint` v3.1.4.

**Comment by davidtheclark** [comment]
@onlywei Pretty sure that the problem you're seeing here was with stylelint itself (https://github.com/stylelint/stylelint/issues/665) and is now fixed, so I'd suggest closing this issue in linter-stylelint. Thanks!

**Comment by 1000ch** [comment]
@davidtheclark :+1:
