### ISSUE TITLE
Should ignore projects when no configuration is found

### ISSUE THREAD

**Issue by davidtheclark** [AtomLinter/linter-stylelint#72]
Right now when I work on a project that doesn't use stylelint but does use CSS files, I get the warning `Unable to run stylelint. No rules found within configuration. Have you provided a "rules" property?`.

I would prefer if linter-stylelint didn't try to run unless it can find a stylelint configuration. What do you think?

**Comment by Arcanemagus** [comment]
Does the "Disable when no config file is found" option not work for you?

**Comment by davidtheclark** [comment]
@Arcanemagus: Apologies! I forgot about that option. I will double-check when I get back to the machine this happened for and probably close this issue.

**Comment by Arcanemagus** [comment]
Cool, let us know how it turns out :wink:.

**Comment by davidtheclark** [comment]
Works fine. My mistake.
