### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of [object String]

### ISSUE THREAD

**Issue by paulrobertlloyd** [AtomLinter/linter-stylelint#73]
Hello. I’m getting the following error when I use the `ignoreFiles` directive. Here is my config:

```
{
    "extends": "/Volumes/Macintosh/Users/paulrobertlloyd/.atom/packages/linter-stylelint/node_modules/stylelint-config-standard",
    "ignoreFiles": [
        "source/_assets/stylesheets/vendor/*.scss"
    ],
    "rules": {
        "at-rule-empty-line-before": [ "always", {
            "except": ["blockless-group", "first-nested"]
        } ],
        "declaration-colon-newline-after": "always-multi-line",
        "function-url-quotes": "none",
        "indentation": 4
    }
}
```

and here is the error generated:

```
TypeError: Cannot assign to read only property '0' of [object String]
    at assignKey (/Users/paulrobertlloyd/.atom/packages/linter-stylelint/node_modules/deep-assign/index.js:28:11)
    at assign (/Users/paulrobertlloyd/.atom/packages/linter-stylelint/node_modules/deep-assign/index.js:43:4)
    at assignKey (/Users/paulrobertlloyd/.atom/packages/linter-stylelint/node_modules/deep-assign/index.js:30:13)
    at assign (/Users/paulrobertlloyd/.atom/packages/linter-stylelint/node_modules/deep-assign/index.js:43:4)
    at deepAssign (/Users/paulrobertlloyd/.atom/packages/linter-stylelint/node_modules/deep-assign/index.js:64:3)
    at then.atom.notifications.addError.detail (/Users/paulrobertlloyd/.atom/packages/linter-stylelint/lib/index.js:131:28)
```

Not sure if this is an AtomLinter issue or related directly to stylelint… I tried running stylelint directly from the CLI to see if I could reproduce, but got a number of different unrelated issues (partly it seems, because it was trying to lint text within comments).

I guess the first question is: is my config file correct?

**Comment by davidtheclark** [comment]
@paulrobertlloyd: From trying to run the stylelint CLI do you have any bugs that we could fix over in the stylelint repo? Your config looks fine to me.

@Arcanemagus Is there a chance the deep-assign library you're using doesn't handle arrays as expected? https://github.com/sindresorhus/deep-assign/issues/4

**Comment by Arcanemagus** [comment]
@davidtheclark @1000ch is the maintainer for this repo, I'm not entirely sure why it isn't just using `Object.assign()` as that is available in a packages direct code files (spawned threads and modules are another story).

@paulrobertlloyd Are you able to share the file you were seeing this on to reproduce this?

**Comment by davidtheclark** [comment]
@paulrobertlloyd I am unable to reproduce this inside or outside of Atom.

**Comment by paulrobertlloyd** [comment]
Hmm, no longer getting this error as of linter-stylelint 1.10.4. However, files that are in my ignoreFiles directive are not being ignored. Will file a separate bug for this.
