### ISSUE TITLE
<style> tag

### ISSUE THREAD

**Issue by JosefJezek** [AtomLinter/linter-stylelint#8]
Please add support for `<style>` tag in html files. We need for Polymer Theme.

https://github.com/StartPolymer/polymer-starter-kit-plus

**Comment by 1000ch** [comment]
I'll consider :)

**Comment by Arcanemagus** [comment]
@JosefJezek This is actually a bit involved. You would need to have something strip out the CSS, feed it into `stylelint` and then somehow map the line/column numbers back to the source file.

**Comment by blake-newman** [comment]
:+1: This would be a great feature for support of Vue

**Comment by blake-newman** [comment]
Added the functionality to stylelint: https://github.com/stylelint/stylelint/pull/1019

Will apply the relevant code to consume this here.
