### ISSUE TITLE
hierarchicalSelectors not working

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-stylelint#82]
From: https://github.com/stylelint/stylelint/issues/708

```js
'indentation': [2, {
  hierarchicalSelectors: true
}]
```

![image](https://cloud.githubusercontent.com/assets/224636/12878753/d5035d18-cdf7-11e5-885a-3caafa3a8694.png)

According to the maintainers I'm using this correctly, it's just not working in linter.

**Comment by Arcanemagus** [comment]
Well, same question that @davidtheclark asked: Does `stylelint` show this as an issue when you run it outside of Atom?

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/12905667/1a82f9de-cea7-11e5-811a-c88be6405289.png)

I've literally spent several hours these past few days trying to file issues for this project.

To be honest, I'm done caring about it enough to run back and forth trying to track down where things are broken and file it in the right place, etc. etc.

stylelint doesn't work with Atom Linter. Get together with the maintainers and figure it out or don't. I don't care.

**Comment by davidtheclark** [comment]
This is an issue with stylelint: https://github.com/stylelint/stylelint/issues/712. So it can be closed here.
